name: Windows build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        include:
#          - {chain: mingw32, cc: gcc}
#          - {chain: mingw64, cc: gcc}
          - {chain: clang64, cc: clang}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.chain}}
          install: make cmake tree
          pacboy: ${{matrix.cc}}:p hdf5:p boost:p opencv:p
      - name: Compile
        run: |
          cd animeloop-cli
          mkdir build && cd build
          cmake -G "MinGw Makefiles" ..
          make animeloop-cli
      - name: Show result
        run: tree
#      - name: Upload .exe
#        uses: actions/upload-artifact@v3
#        with:
#          name: activate-windows.exe
#          path: |
#            activate-windows-*.exe
